import { Container } from '@/components/shared/Container';
import { Header } from '@/components/shared/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header className="border-b-gray-200" hasCheckout={true} />
        {children}
      </Container>
    </main>
  );
}
